services:
  app:
    image: mysociety/voting-data:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/voting_data      
    volumes:
      - ./:/workspaces/voting_data/